version: '3.4'

services:
    db:
        image: postgres:12-alpine
        ports:
            - "${DB_PORT}:5432"
        environment:
            - POSTGRES_DB=DB
            - POSTGRES_USER="${DB_USERNAME}"
            - POSTGRES_PASSWORD="${DB_PASSWORD}"
            - PGGSSENCMODE=disable
        volumes:
            - "./dbdata:/var/lib/postgresql/data"
    dev: 
        build:
            context: .
            target: nestjs-dev

        ports: 
            - "3000:3000"
        volumes:
            - "./:/usr/src/app/"
        command: "yarn run start:dev"
