version: '3.4'

services:
    db:
        image: postgres:12-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB="${DB_NAME}"
            - POSTGRES_USER="${DB_USERNAME}"
            - POSTGRES_PASSWORD="${DB_PASSWORD}"
            - PGGSSENCMODE=disable
        volumes:
            - "./dbdata:/var/lib/postgresql/data"
volumes:
    dbdata: 
