version: '3.4'

services:
    postgres:
        image: postgres:12-alpine
        ports:
            - "${DB_PORT}:5432"
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_HOST_AUTH_METHOD=trust
            - PGGSSENCMODE=disable
        volumes:
            - "./dbdata:/var/lib/postgresql/data"
    pgadmin:
        image: dpage/pgadmin4
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=root
        ports:
            - "5050:80"
        depends_on:
            - postgres
    dev:
        build:
            context: .
            target: nestjs-dev
        ports:
            - "3000:3000"
        volumes:
            - "./:/usr/src/app/"
        command: "yarn run start:dev"
        depends_on:
            - postgres
